#!groovy
node('maven') {
   // define commands
   def mvnCmd = "mvn -s pipeline/deploy/configuration/maven-settings.xml"

   stage ('Execute Integration Tests') {
     //Jenkins & gogs are in the same namespace
     git branch: 'master', url: 'http://gogs:3000/serhat/mlbparks.git'
     sh "${mvnCmd} test -Dskip.unit.tests"
   }

   def tag="blue"
   def altTag="green"

   stage ('Deploy PROD') {
    echo "Deploying to prod..."
    //Find the active service
    sh "oc get route mlbparks -n serhat-hw-prod -o jsonpath='{ .spec.to.name }' > activeservice"
    activeService = readFile('activeservice').trim()
    echo "Active Service : ${activeService}"
    if (activeService == "mlbparks-blue") {
        tag = "green"
        altTag = "blue"
    }
    echo "Deploying  mlbparks-${tag}"
    openshiftTag(sourceStream: 'mlbparks', sourceTag: 'latest', namespace: 'serhat-hw-dev', destinationStream: 'mlbparks', destinationTag: "prod-${tag}", destinationNamespace: 'serhat-hw-dev')
    sleep 25
    echo "Verifying the deployment..."
    openshiftVerifyDeployment(deploymentConfig: "mlbparks-${tag}", replicaCount: 1, verifyReplicaCount: true, namespace: 'serhat-hw-prod')
     
   }
    
    stage ('Smoke Tests in PROD (Not Live)! This is your part to play!!'){
                                           
    }


   stage ('Approve to go Live (You have 30 minutes to complete this step) ??') {
     
     timeout(time:30, unit:'MINUTES') {
        input message:'Go Live in Production (switch to new version ${tag} )?' , ok: "Promote ${tag}"
     }
   
     sh "oc set route-backends mlbparks mlbparks-${tag}=100 mlbparks-${altTag}=0 -n serhat-hw-prod"
     sh "oc label svc mlbparks-${altTag} state=idle --overwrite -n serhat-hw-prod"
     sh "oc label svc mlbparks-${tag} state=active --overwrite -n serhat-hw-prod"
     echo "Now the prod deployment switched to the ${tag} version"
   }

}